"""add oauth

Revision ID: 8eb7162afee7
Revises: f0ba66f2e9b2
Create Date: 2020-11-01 16:10:08.345978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb7162afee7'
down_revision = 'f0ba66f2e9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_column('participants', 'password')
    op.add_column('participants', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index('participant_email', 'participants', ['email', 'tasting_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admins',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    op.drop_constraint('participant_email', 'participants', type_='unique')
    op.drop_column('participants', 'email')
    op.add_column('participants', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###
